title: Bridge System Notes
description: System notes for Souvik (souvik0612) and Sounak (sounakn)
remote_theme: sighingnow/jekyll-gitbook
toc:
    enabled: true
    h_min: 1
    h_max: 3
collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others
