title: Bridge System Notes
description: System notes for Souvik (souvik0612) and Sounak (sounakn)
remote_theme: sighingnow/jekyll-gitbook
toc:
    enabled: true
    h_min: 1
    h_max: 3
collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

ordered_collections:
  - posts
  - pages
  - others
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
