name: Convert Markdown to PDF

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y wkhtmltopdf

      - name: Convert README.md to PDF
        run: pandoc README.md -o README.pdf --pdf-engine=wkhtmltopdf

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.pdf
          git commit -m 'Auto-generate PDF from README.md'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
